:toc:

# Contributors Guide

## Local Environment

.Tools
|===
| Tool | Purpose

| https://gradle.org[Gradle]
| Used to run unit tests, package the JPI, and publish the plugin

| https://github.com/casey/just[Just]
| A task runner. Used here to automate common commands used during development.

| https://www.docker.com/get-started[Docker]
| Used to build the documentation for local preview

|===


## Running Tests

To run all the tests, run: 

[source,bash]
----
just test
----

The gradle test report is published to `build/target/tests/test/index.html`

### Execute tests for a specific class

To run tests for a specific Class, `StepWrapperSpec` for example, run:

[source,bash]
----
just test '*.StepWrapperSpec'
----

### Code Coverage

By default, JaCoCo code coverage is enabled when running test.

Once executed, the JaCoCo coverage report can be found at: `build/reports/jacoco/test/html/index.html`

To disable this, run:

[source, bash]
----
just --set coverage false test
----

## Linting

This project uses https://github.com/diffplug/spotless[Spotless] and https://github.com/CodeNarc/CodeNarc[CodeNarc] to perform linting. The CodeNarc rule sets for `src/main` and `src/test` can be found in `config/codenarc/rules.groovy` and `config/codenarc/rulesTest.groovy`, respectively. 

Once executed, the reports can be found at `build/reports/codenarc/main.html` and `build/reports/codenarc/test.html`.

To execute linting, run: 

[source,groovy]
----
just lint
----

## Building the JPI

To build the JPI, run: 

[source, bash]
----
just jpi
----

Once built, the JPI will be located at `build/libs/templating-engine.jpi`

## Building the Documentation

This project uses https://antora.org/[Antora] to build the documentation.

To build the documentation, run: 

[source, bash]
----
just docs
----

Once built, the documentation can be viewed at `docs/html/index.html`

### Customizing the documentation output directory

The `docsDir` justfile variable configures the output directory. 

To modify the output directory, run:

[source, bash]
----
just --set docsDir some/other/directory docs
----

## Publishing JTE

**If you have the permission**, you can cut a new release of JTE by running `just release <versionNumber>`. 

For example: 

[source, bash]
----
just release 2.0.4
----

This will:

1. create a `release/2.0.4` branch
2. update the version in the `build.gradle`
3. update the version in the `docs/antora.yml`
4. push those changes
5. create a `2.0.4` tag
6. publish the JPI

[NOTE]
====
Don't forget to go to the https://github.com/jenkinsci/templating-engine-plugin/releases[Releases Page] to officially release JTE with the current change log based off the most recent tag.
====

## Run a containerized Jenkins

### Mounting local libraries for testing