name: CI
on:
  pull_request:
    branches: 
      - main
jobs:
  Spotless:
    runs-on: ubuntu-latest
    if: github.repository == 'jenkinsci/templating-engine-plugin'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon spotlessCheck
  CodeNarc:
    runs-on: ubuntu-latest
    if: github.repository == 'jenkinsci/templating-engine-plugin'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon codenarc
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: codenarc-results
          path: build/reports
  MarkdownLint:
    runs-on: ubuntu-latest
    container:
      image: davidanson/markdownlint-cli2:0.4.0
      volumes:
        - ${{ github.workspace }}:/app
      options: -w /app --entrypoint sh
    if: github.repository == 'jenkinsci/templating-engine-plugin'
    steps:
      - name: markdownlint-cli
        run: ls && pwd && markdownlint-cli2
  Unit_Test:
    runs-on: ubuntu-latest
    if: github.repository == 'jenkinsci/templating-engine-plugin'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: --no-daemon test jacocoTestReport
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-results
        path: build/reports
  Build_JPI:
    runs-on: ubuntu-latest
    if: github.repository == 'jenkinsci/templating-engine-plugin'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: --no-daemon jpi
    - uses: actions/upload-artifact@v1
      with:
        name: jpi
        path: build/libs/templating-engine.hpi
