name: docs
on:
  push:
    branches: 
      - main
jobs:
  DeployDocs:
    runs-on: ubuntu-latest
    if: github.repository == 'jenkinsci/templating-engine-plugin'
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy the Docs"
        run: just update-docs