# .github/workflows/gradle-build-pr.yml
name: Gradle Test
on:
  pull_request:
    branches: 
      - master
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: --no-daemon test --scan
